{
  "swagger": "2.0",
  "info": {
    "version": "1.x",
    "title": "Handmade ",
    "contact": {
      "name": "Marigrace Silva",
      "email": "mksss161297@gmail.com"
    }
  },
  "host": "127.0.0.1:8000",
  "basePath": "/",
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header",
      "description": "Ingresa una token válida**"
    }
  },
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/handmade/registrar/": {
      "post": {
        "summary": "Crear un nuevo cliente",
        "tags": [
          "Clientes"
        ],
        "operationId": "/handmade/registrar",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1handmade~1registrar~1request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/clientes/": {
      "get": {
        "summary": "Clientes activos",
        "tags": [
          "Búsquedas"
        ],
        "operationId": "/handmade/clientes/",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/buscar-cliente": {
      "get": {
        "summary": "Búsqueda cliente por nombre ó documento",
        "tags": [
          "Búsquedas"
        ],
        "operationId": "/handmade/buscar-cliente",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "nombre",
            "in": "query",
            "required": false,
            "type": "string",
            "description": ""
          },
          {
            "name": "documento",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int32",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/login-custom": {
      "post": {
        "summary": "Login usuario",
        "tags": [
          "Login"
        ],
        "operationId": "/handmade/login-custom",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1handmade~1login-custom-request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/refresh-token": {
      "post": {
        "summary": "/handmade/refresh-token",
        "tags": [
          "Login"
        ],
        "operationId": "/handmade/refresh-token",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1handmade~1refresh-token-request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/me": {
      "get": {
        "summary": "Perfil Usuario",
        "tags": [
          "Login"
        ],
        "operationId": "/handmade/me",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "security": [
          {
            "Bearer": []
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/verify-token": {
      "post": {
        "summary": "/handmade/verify-token",
        "tags": [
          "Login"
        ],
        "operationId": "/handmade/verify-token",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/admin/{id}": {
      "get": {
        "summary": "Buscar cliente por id",
        "tags": [
          "Administrador"
        ],
        "operationId": "/handmade/cliente/:id",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "patch": {
        "summary": "Acualización de perfil",
        "tags": [
          "Administrador"
        ],
        "operationId": "/handmade/cliente/:id1",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1handmade~1cliente~1%3Aidrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "put": {
        "summary": "Actualización completa de usuario",
        "tags": [
          "Administrador"
        ],
        "operationId": "/handmade/cliente/:id2",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1handmade~1cliente~1%3Aidrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "delete": {
        "summary": "Eliminar un usuario",
        "tags": [
          "Administrador"
        ],
        "operationId": "/handmade/cliente/:id3",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/categorias/": {
      "post": {
        "summary": "Crear categorias",
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "Categoria"
        ],
        "operationId": "/handmade/categorias/",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1handmade~1categorias~1request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "get": {
        "summary": "Todas las categorias activas",
        "tags": [
          "Categoria"
        ],
        "operationId": "Get/handmade/categorias/",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/categoria/{id}": {
      "get": {
        "summary": "Buscar categoría por id",
        "tags": [
          "Categoria/{id}"
        ],
        "operationId": "/handmade/categoria/:id",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "put": {
        "summary": "Actualización completa categoria",
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "Categoria/{id}"
        ],
        "operationId": "/handmade/categoria/:id1",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1handmade~1categoria~11request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "delete": {
        "summary": "Eliminar categoria",
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "Categoria/{id}"
        ],
        "operationId": "/handmade/categoria/:id2",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/productos/": {
      "post": {
        "summary": "Crear productos",
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "Productos"
        ],
        "operationId": "/handmade/productos/",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1handmade~1productos~1request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "get": {
        "summary": "Todos los productos activos",
        "tags": [
          "Productos"
        ],
        "operationId": "/handmade/productos",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/subir-imagen/": {
      "post": {
        "summary": "/handmade/subir-imagen/",
        "tags": [
          "Subir imagen"
        ],
        "operationId": "/handmade/subir-imagen/",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "imagen",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/producto/{id}": {
      "get": {
        "summary": "Producto por id",
        "tags": [
          "Producto/{id}"
        ],
        "operationId": "/handmade/producto/:id",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "patch": {
        "summary": "Actualización parcial de producto",
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "Producto/{id}"
        ],
        "operationId": "Patch/handmade/producto/:id1",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1handmade~1producto~1%3Aidrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "put": {
        "summary": "Actualización total de producto",
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "Producto/{id}"
        ],
        "operationId": "/handmade/producto/:id2",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1handmade~1producto~1%3Aidrequest1"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "delete": {
        "summary": "Eliminar producto ",
        "security": [
          {
            "Bearer": []
          }
        ],
        "tags": [
          "Producto/{id}"
        ],
        "operationId": "Delete/handmade/producto/:id3",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/orden-compra/": {
      "post": {
        "summary": "Crear orden de compra",
        "tags": [
          "Orden"
        ],
        "operationId": "/handmade/orden-compra/",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1handmade~1orden-compra~1-request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/orden/{id}": {
      "get": {
        "summary": "Ordenes de compra",
        "tags": [
          "Orden/{id}"
        ],
        "operationId": "/handmade/orden/:id",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int64"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/filtro-productos": {
      "get": {
        "summary": "/handmade/filtro-productos",
        "tags": [
          "Consultas"
        ],
        "operationId": "/handmade/filtro-productos",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "nombre",
            "in": "query",
            "required": false,
            "type": "string",
            "description": ""
          },
          {
            "name": "precio",
            "in": "query",
            "required": false,
            "type": "number",
            "format": "double"
          },
          {
            "name": "created_at",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "date-time",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/producto-categoria": {
      "get": {
        "summary": "Productos por categoria",
        "tags": [
          "Consultas"
        ],
        "operationId": "/handmade/producto-categoria",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "categoria_id",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/filtro-orden": {
      "get": {
        "summary": "Cabecera ordenes",
        "tags": [
          "Consultas"
        ],
        "operationId": "/handmade/filtro-orden/",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "direccion",
            "in": "query",
            "required": false,
            "type": "string",
            "description": ""
          },
          {
            "name": "correo",
            "in": "query",
            "required": false,
            "type": "string",
            "description": ""
          },
          {
            "name": "fecha",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "date-time",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/handmade/orden-cliente": {
      "get": {
        "summary": "Ordenes por cliente",
        "tags": [
          "Consultas"
        ],
        "operationId": "/handmade/orden-cliente",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "cliente_id",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/facturacion/generar-comprobante/": {
      "post": {
        "summary": "Generar documento de venta",
        "tags": [
          "Facturación"
        ],
        "operationId": "/facturacion/generar-comprobante/",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/~1facturacion~1generar-comprobante~1-request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "/handmade/registrar/request": {
      "title": "/handmade/registrar/request",
      "example": {
        "clienteNombre": "Marigrace",
        "clienteTipoDoc": 2,
        "clienteNroDoc": 78549632,
        "clienteDireccion": "Av Cayma",
        "clienteTipo": 2,
        "clienteCorreo": "kim@gmail.com",
        "password": "Welcome123!"
      },
      "type": "object",
      "properties": {
        "clienteNombre": {
          "type": "string"
        },
        "clienteTipoDoc": {
          "type": "integer",
          "format": "int32"
        },
        "clienteNroDoc": {
          "type": "integer",
          "format": "int32"
        },
        "clienteDireccion": {
          "type": "string"
        },
        "clienteTipo": {
          "type": "integer",
          "format": "int32"
        },
        "clienteCorreo": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "clienteNombre",
        "clienteTipoDoc",
        "clienteNroDoc",
        "clienteDireccion",
        "clienteTipo",
        "clienteCorreo",
        "password"
      ]
    },
    "/handmade/login-custom-request": {
      "title": "/handmade/login-custom-request",
      "example": {
        "clienteCorreo": "mksss161297@gmail.com",
        "password": "123456"
      },
      "type": "object",
      "properties": {
        "clienteCorreo": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "clienteCorreo",
        "password"
      ]
    },
    "/handmade/refresh-token-request": {
      "title": "/handmade/refresh-token-request",
      "example": {
        "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTYzNTQ4MDQ4NywianRpIjoiM2MyMTUzNTg1NTlhNGQ3MmE2NTA0MTQ0NGIxMmU5MmQiLCJ1c2VyX2lkIjozLCJ1c2VyX21haWwiOiJjY2MxYWFjY0BnbWFpbC5jb20iLCJtZW5zYWplIjoiQ3VzdG9tIn0.Gem9LR3URME75ApWDllkkbwtdtdH8Ef0fYGqG1_bR2Y"
      },
      "type": "object",
      "properties": {
        "refresh": {
          "type": "string"
        }
      },
      "required": [
        "refresh"
      ]
    },
    "/handmade/cliente/:idrequest": {
      "title": "/handmade/cliente/:idrequest",
      "example": {
        "clienteNombre": "Marigrace Silva Salas",
        "clienteTipoDoc": 1,
        "clienteNroDoc": "72750134",
        "clienteDireccion": "Av Cayma",
        "clienteTipo": 1,
        "clienteCorreo": "mksss161297@gmail.com",
        "password": "Welcome123!"
      },
      "type": "object",
      "properties": {
        "clienteNombre": {
          "type": "string"
        },
        "clienteTipoDoc": {
          "type": "integer",
          "format": "int32"
        },
        "clienteNroDoc": {
          "type": "string"
        },
        "clienteDireccion": {
          "type": "string"
        },
        "clienteTipo": {
          "type": "integer",
          "format": "int32"
        },
        "clienteCorreo": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "clienteNombre",
        "clienteTipoDoc",
        "clienteNroDoc",
        "clienteDireccion",
        "clienteTipo",
        "clienteCorreo",
        "password"
      ]
    },
    "/handmade/categorias/request": {
      "title": "/handmade/categorias/request",
      "example": {
        "categoriaNombre": "Aniversarios",
        "categoriaEstado": "True"
      },
      "type": "object",
      "properties": {
        "categoriaNombre": {
          "type": "string"
        },
        "categoriaEstado": {
          "type": "string"
        }
      },
      "required": [
        "categoriaNombre",
        "categoriaEstado"
      ]
    },
    "/handmade/categoria/1request": {
      "title": "/handmade/categoria/1request",
      "example": {
        "categoriaNombre": "Aniversarios"
      },
      "type": "object",
      "properties": {
        "categoriaNombre": {
          "type": "string"
        }
      },
      "required": [
        "categoriaNombre"
      ]
    },
    "/handmade/productos/request": {
      "title": "/handmade/productos/request",
      "example": {
        "productoNombre": "Caja Artesanal 1",
        "productoDescripcion": "Detalles Especiales",
        "productoPrecio": "40",
        "productoCantidad": 100,
        "productoImagen": "http://res.cloudinary.com/dvnfpdtlz/image/upload/v1633996383/ayz9xspo1f3uyyptbtee.jpg",
        "categoria": 1
      },
      "type": "object",
      "properties": {
        "productoNombre": {
          "type": "string"
        },
        "productoDescripcion": {
          "type": "string"
        },
        "productoPrecio": {
          "type": "string"
        },
        "productoCantidad": {
          "type": "integer",
          "format": "int32"
        },
        "productoImagen": {
          "type": "string"
        },
        "categoria": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "productoNombre",
        "productoDescripcion",
        "productoPrecio",
        "productoCantidad",
        "productoImagen",
        "categoria"
      ]
    },
    "/handmade/producto/:idrequest": {
      "title": "/handmade/producto/:idrequest",
      "example": {
        "productoNombre": "Caja musical pequeña"
      },
      "type": "object",
      "properties": {
        "productoNombre": {
          "type": "string"
        }
      },
      "required": [
        "productoNombre"
      ]
    },
    "/handmade/producto/:idrequest1": {
      "title": "/handmade/producto/:idrequest1",
      "example": {
        "productoNombre": "Caja musical",
        "productoDescripcion": "s",
        "productoImagen": "pugo.jpg",
        "productoPrecio": 19.1,
        "categoria": 2
      },
      "type": "object",
      "properties": {
        "productoNombre": {
          "type": "string"
        },
        "productoDescripcion": {
          "type": "string"
        },
        "productoImagen": {
          "type": "string"
        },
        "productoPrecio": {
          "type": "number",
          "format": "double"
        },
        "categoria": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "productoNombre",
        "productoDescripcion",
        "productoImagen",
        "productoPrecio",
        "categoria"
      ]
    },
    "/handmade/orden-compra/-request": {
      "title": "/handmade/orden-compra/-request",
      "example": {
        "cliente_id": 1,
        "detalle": [
          {
            "producto_id": 1,
            "cantidad": 2
          },
          {
            "producto_id": 1,
            "cantidad": 2
          }
        ]
      },
      "type": "object",
      "properties": {
        "cliente_id": {
          "type": "integer",
          "format": "int32"
        },
        "detalle": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Detalle"
          }
        }
      },
      "required": [
        "cliente_id",
        "detalle"
      ]
    },
    "Detalle": {
      "title": "Detalle",
      "example": {
        "producto_id": 1,
        "cantidad": 2
      },
      "type": "object",
      "properties": {
        "producto_id": {
          "type": "integer",
          "format": "int32"
        },
        "cantidad": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "producto_id",
        "cantidad"
      ]
    },
    "/facturacion/generar-comprobante/-request": {
      "title": "/facturacion/generar-comprobante/-request",
      "example": {
        "ordenId": 2,
        "tipoComprobante": "BOLETA",
        "numeroDocumento": 72750134
      },
      "type": "object",
      "properties": {
        "ordenId": {
          "type": "integer",
          "format": "int32"
        },
        "tipoComprobante": {
          "type": "string"
        },
        "numeroDocumento": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "ordenId",
        "tipoComprobante",
        "numeroDocumento"
      ]
    }
  },
  "tags": [
    {
      "name": "Clientes"
    },
    {
      "name": "Búsquedas"
    },
    {
      "name": "Login"
    },
    {
      "name": "Administrador"
    },
    {
      "name": "Categoria"
    },
    {
      "name": "Categoria/{id}"
    },
    {
      "name": "Productos"
    },
    {
      "name": "Subir imagen"
    },
    {
      "name": "Producto/{id}"
    },
    {
      "name": "Orden"
    },
    {
      "name": "Orden/{id}"
    },
    {
      "name": "Consultas"
    },
    {
      "name": "Facturación"
    }
  ]
}